2018-06-07 08:13:41,585 INFO: Database Repository startup [in /home/tmas/workspace/dbrepo/app/__init__.py:52]
2018-06-07 08:13:41,642 INFO: Database Repository startup [in /home/tmas/workspace/dbrepo/app/__init__.py:52]
2018-06-07 08:13:41,680 INFO: Database Repository startup [in /home/tmas/workspace/dbrepo/app/__init__.py:52]
2018-06-07 08:13:41,701 INFO: Database Repository startup [in /home/tmas/workspace/dbrepo/app/__init__.py:52]
2018-06-07 08:13:48,250 ERROR: Exception on /favicon.ico [GET] [in /home/tmas/workspace/dbrepo/venv/local/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/tmas/workspace/dbrepo/venv/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/tmas/workspace/dbrepo/venv/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/tmas/workspace/dbrepo/venv/local/lib/python2.7/site-packages/flask/app.py", line 1713, in handle_user_exception
    return self.handle_http_exception(e)
  File "/home/tmas/workspace/dbrepo/venv/local/lib/python2.7/site-packages/flask/app.py", line 1644, in handle_http_exception
    return handler(e)
  File "/home/tmas/workspace/dbrepo/app/errors/handlers.py", line 8, in not_found_error
    return render_template('errors/404.html'), 404
  File "/home/tmas/workspace/dbrepo/venv/local/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/tmas/workspace/dbrepo/venv/local/lib/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/tmas/workspace/dbrepo/venv/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/tmas/workspace/dbrepo/venv/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tmas/workspace/dbrepo/app/templates/errors/404.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/tmas/workspace/dbrepo/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/tmas/workspace/dbrepo/venv/local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/tmas/workspace/dbrepo/venv/local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/tmas/workspace/dbrepo/venv/local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/tmas/workspace/dbrepo/venv/local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/tmas/workspace/dbrepo/app/templates/base.html", line 46, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/tmas/workspace/dbrepo/app/templates/errors/404.html", line 5, in block "app_content"
    <p><a href="{{ url_for('index') }}">Back</a></p>
  File "/home/tmas/workspace/dbrepo/venv/local/lib/python2.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/tmas/workspace/dbrepo/venv/local/lib/python2.7/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/tmas/workspace/dbrepo/venv/local/lib/python2.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/tmas/workspace/dbrepo/venv/local/lib/python2.7/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
2018-06-07 08:22:23,641 INFO: Database Repository startup [in /home/tmas/workspace/dbrepo/app/__init__.py:52]
2018-06-07 08:22:23,650 INFO: Database Repository startup [in /home/tmas/workspace/dbrepo/app/__init__.py:52]
2018-06-07 08:22:23,725 INFO: Database Repository startup [in /home/tmas/workspace/dbrepo/app/__init__.py:52]
2018-06-07 08:22:23,761 INFO: Database Repository startup [in /home/tmas/workspace/dbrepo/app/__init__.py:52]
2018-06-07 08:32:03,666 INFO: Database Repository startup [in /home/tmas/workspace/dbrepo/app/__init__.py:52]
2018-06-07 08:32:03,728 INFO: Database Repository startup [in /home/tmas/workspace/dbrepo/app/__init__.py:52]
2018-06-07 08:32:03,830 INFO: Database Repository startup [in /home/tmas/workspace/dbrepo/app/__init__.py:52]
2018-06-07 08:32:03,869 INFO: Database Repository startup [in /home/tmas/workspace/dbrepo/app/__init__.py:52]
2018-06-07 10:43:32,740 INFO: Database Repository startup [in /home/tmas/workspace/dbrepo/app/__init__.py:52]
2018-06-07 10:43:32,755 INFO: Database Repository startup [in /home/tmas/workspace/dbrepo/app/__init__.py:52]
2018-06-07 10:43:32,830 INFO: Database Repository startup [in /home/tmas/workspace/dbrepo/app/__init__.py:52]
2018-06-07 10:43:32,852 INFO: Database Repository startup [in /home/tmas/workspace/dbrepo/app/__init__.py:52]
2018-06-07 10:46:05,699 INFO: Database Repository startup [in /home/tmas/workspace/dbrepo/app/__init__.py:52]
2018-06-07 10:46:26,484 INFO: Database Repository startup [in /home/tmas/workspace/dbrepo/app/__init__.py:52]
2018-06-07 10:48:04,643 INFO: Database Repository startup [in /home/tmas/workspace/dbrepo/app/__init__.py:52]
2018-06-07 10:58:48,961 INFO: Database Repository startup [in /home/tmas/workspace/dbrepo/app/__init__.py:52]
2018-06-07 11:00:54,617 INFO: Database Repository startup [in /home/tmas/workspace/dbrepo/app/__init__.py:52]
2018-06-07 14:12:53,208 INFO: Database Repository startup [in /home/tmas/workspace/dbrepo/app/__init__.py:52]
2018-06-07 14:12:53,208 INFO: Database Repository startup [in /home/tmas/workspace/dbrepo/app/__init__.py:52]
2018-06-07 14:12:53,235 INFO: Database Repository startup [in /home/tmas/workspace/dbrepo/app/__init__.py:52]
2018-06-07 14:12:53,246 INFO: Database Repository startup [in /home/tmas/workspace/dbrepo/app/__init__.py:52]
2018-06-07 14:13:02,881 ERROR: Exception on /index [GET] [in /home/tmas/workspace/dbrepo/venv/local/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/tmas/workspace/dbrepo/venv/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/tmas/workspace/dbrepo/venv/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/tmas/workspace/dbrepo/venv/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tmas/workspace/dbrepo/venv/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/tmas/workspace/dbrepo/venv/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/tmas/workspace/dbrepo/venv/local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/tmas/workspace/dbrepo/app/main/routes.py", line 21, in index
    posts = current_user.followed_posts().paginate(
  File "/home/tmas/workspace/dbrepo/venv/local/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'User' object has no attribute 'followed_posts'
2018-06-07 14:41:02,242 INFO: Database Repository startup [in /home/tmas/workspace/dbrepo/app/__init__.py:52]
2018-06-07 14:41:02,336 INFO: Database Repository startup [in /home/tmas/workspace/dbrepo/app/__init__.py:52]
2018-06-07 14:41:02,395 INFO: Database Repository startup [in /home/tmas/workspace/dbrepo/app/__init__.py:52]
2018-06-07 14:41:02,440 INFO: Database Repository startup [in /home/tmas/workspace/dbrepo/app/__init__.py:52]
2018-06-07 14:41:09,324 ERROR: Exception on /index [GET] [in /home/tmas/workspace/dbrepo/venv/local/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/tmas/workspace/dbrepo/venv/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/tmas/workspace/dbrepo/venv/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/tmas/workspace/dbrepo/venv/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/tmas/workspace/dbrepo/venv/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/tmas/workspace/dbrepo/venv/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/tmas/workspace/dbrepo/venv/local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/tmas/workspace/dbrepo/app/main/routes.py", line 22, in index
    posts = current_user.followed_posts().paginate(
  File "/home/tmas/workspace/dbrepo/venv/local/lib/python2.7/site-packages/werkzeug/local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'User' object has no attribute 'followed_posts'
2018-06-07 14:42:17,281 INFO: Database Repository startup [in /home/tmas/workspace/dbrepo/app/__init__.py:52]
2018-06-07 14:42:17,366 INFO: Database Repository startup [in /home/tmas/workspace/dbrepo/app/__init__.py:52]
2018-06-07 14:42:17,486 INFO: Database Repository startup [in /home/tmas/workspace/dbrepo/app/__init__.py:52]
